# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180505_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='\u89c6\u9891id'),
        ),
    ]
