# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-24 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u89c6\u9891\u7ba1\u7406', 'verbose_name_plural': '\u89c6\u9891\u7ba1\u7406'},
        ),
    ]
