# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-05 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180424_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u89c6\u9891\u4fe1\u606f', 'verbose_name_plural': '\u89c6\u9891\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='\u5f00\u53d1', max_length=20, verbose_name='\u89c6\u9891\u5206\u7c7b'),
        ),
    ]
