# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180505_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
