# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='videores',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='videores',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d'),
        ),
    ]
