# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='\u89c6\u9891\u6807\u7b7e'),
        ),
    ]
