# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20180519_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='detail',
            field=models.TextField(verbose_name='\u89c6\u9891\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='video',
            name='times',
            field=models.IntegerField(default=0, verbose_name='\u89c6\u9891\u65f6\u957f'),
        ),
    ]
